add modal 'Add water' for mobile
AndriyITua/Innov8ors-frontend pull request #16
Opened 2024-10-19 21:03 UTC by kononova1986

Модалка мобильной версии для добавления воды.
Кнопки для увеличения и уменьшения объема воды.
Реализовано поле ввода для записи времени, которое по умолчанию показывает локальное время.
Добавлен лоадер при сохранении данных.

2024-10-20 11:40 UTC, kononova1986 commented
Сделала 50мл по умолчанию. Кнопка Save не кликабельна если добавленная вода 0 или 5000.

2024-10-20 12:51 UTC, kononova1986 commented
Добавила useEffect так как кнопка Save через раз сохраняла нулевое значение. Добавила дизайн таблетку и десктоп

2024-10-20 13:04 UTC, AndriyITua requested changes
В цій гілці перевіряю тільки мобільну версію, всі інші через нові гілки. 
1. Кнопка мінус (–) не працює
2. Коли нуль, то кнопку сірою зробити чи такою як ми колись робили на проекті js (типу взагалі не клікабельною)

2024-10-20 15:48 UTC, kononova1986 commented
Добавила стили к неактивной кнопке. Модалка открывается по клику на кнопку  Add water

2024-10-20 16:01 UTC, kononova1986 commented
Кнопки + и - работают и обновляют переменную {water} корректно (исправила)

2024-10-20 21:23 UTC, AndriyITua requested changes
Тобі треба було тільки на кнопку, яка вже була створена, повісити модалку addwater. В мене показує, що ти переробила код, який вже прийнятий від Володі (повзунок)

2024-10-21 16:28 UTC, AndriyITua approved these changes
Перевірено

2024-10-21 16:28 UTC, merged