add shared layout component and outlet for other routes
AndriyITua/Innov8ors-frontend pull request #3
Opened 2024-10-16 18:50 UTC by andrewwwmatsko

2024-10-16 22:04 UTC, AndriyITua commented on src/components/App/App.jsx
> +              path="welcome"
Не правильно вказано шлях. Потрібно /welcome

2024-10-16 22:04 UTC, AndriyITua commented on src/components/App/App.jsx
> +              path="signup"
Не правильно вказано шлях. Потрібно /signup

2024-10-16 22:05 UTC, AndriyITua commented on src/components/App/App.jsx
> +              path="signin"
Не правильно вказано шлях. Потрібно /signin

2024-10-16 22:08 UTC, AndriyITua commented on src/components/App/App.jsx
Переглянь внесені тобою зміни у цьому файлі ще раз

2024-10-16 22:10 UTC, AndriyITua requested changes
Потрібно внести правки

2024-10-17 17:30 UTC, andrewwwmatsko commented on src/components/App/App.jsx
Оскільки це вкладений маршрут, то при додаванні / шлях буде //home.

2024-10-17 19:07 UTC, AndriyITua approved these changes

2024-10-17 19:07 UTC, merged