add scroll modal
AndriyITua/Innov8ors-frontend pull request #49
Opened 2024-10-23 11:21 UTC by kononova1986

Добавила скрол в модалке и лодер.
![Screenshot_401](https://github.com/user-attachments/assets/c366d5fe-b06d-49d0-be22-f4ce2ba7e0d0)

2024-10-23 12:44 UTC, AndriyITua requested changes
1. В тебе модалка сама рухається, а модалка повинна бути фіксована по центру і прикріплена до верху сторінки + відступ по макету.
2. Я просив всіх, хто має модалку повістити на неї Михайла зміну (писав в тг загальній) і глянути чи в вас задній фон не рухається. В тебе він рухається

2024-10-23 18:53 UTC, kononova1986 commented
Добавила стили hidden на body по открытию модалки и удалила по закрытию. Добавила на свою AddWater и по согласованию с Вовой на его ModalEntered

2024-10-23 21:45 UTC, AndriyITua requested changes
Не можу прийняти твій пулреквест, бо ти зробила так, щоб навіть при закритій модалці контент головної сторінки не можна свайпати + ти зробила так, що модалка рухається, а повинно бути, щоб контент в модалці рухався. Якщо ти натиснеш на edit в My daily norma, то зрозумієш (але там треба ще справа приховати повзунок)

2024-10-24 10:10 UTC, kononova1986 commented
Андрей, у меня локально модалка прокручивается если не помещается на странице, задний фон на месте. по закрытию страница скролится. Исправила себе и Вове  AddWater и ModalEntered
![Screenshot_410](https://github.com/user-attachments/assets/3641de16-5afd-4047-9f77-61c21571d95c)
![Screenshot_409](https://github.com/user-attachments/assets/c572fbc7-d26c-467b-a9db-332b1b8ea9cb)
![Screenshot_408](https://github.com/user-attachments/assets/d31d2e33-a1bd-49a4-86c1-202e09642bab)

2024-10-24 12:17 UTC, AndriyITua approved these changes
Перевірено

2024-10-24 12:17 UTC, merged