Header user
AndriyITua/Innov8ors-frontend pull request #76
Opened 2024-10-26 18:09 UTC by MikhayloBil

2024-10-26 18:17 UTC, andrewwwmatsko commented on src/components/UserLogo/UserLogo.jsx
> +    const userId = "64e70c21a1d0f93e33c8f2a6";
чому хардкодимо айді?

2024-10-26 18:17 UTC, andrewwwmatsko commented on src/components/UserLogo/UserLogo.jsx
> +  const user = useSelector(state => state.user); // Використовуємо user з нового слайсу
коментарі не треба

2024-10-26 18:17 UTC, andrewwwmatsko commented on src/components/UserLogo/UserLogo.jsx
> +        {/* Використовуємо username або email */}
коментарі забираємо

2024-10-26 18:17 UTC, andrewwwmatsko commented on src/components/UserLogo/UserLogo.jsx
> +        {/* Відображаємо фото, якщо воно є, або ініціал */}
і тут

2024-10-26 18:19 UTC, andrewwwmatsko commented on src/redux/user/userSlice.js
> +const initialState = {
gender?

2024-10-26 18:19 UTC, andrewwwmatsko commented on src/redux/auth/operationLogin.js
> +      console.log(response.data);
зайве

2024-10-26 18:21 UTC, andrewwwmatsko commented on src/redux/auth/operationUser.js
> +axios.defaults.baseURL = "https://innov8ors-backend.onrender.com";
defaults поставлений в operationLogin, можна не дублювати, бо воно встановлюється глобально

2024-10-26 18:21 UTC, andrewwwmatsko commented on src/redux/auth/operationUser.js
> +axios.defaults.withCredentials = true;
так само і це

2024-10-26 18:26 UTC, andrewwwmatsko requested changes
1. Забрати всі коментарі і консоль логи
2. Можливо варто записувати дані про юзера в auth.user, а не створювати ще один такий самий обʼєкт ?
3. Забув в редакс записувати гендер

+ перечитай коменти до рядків, які лишив

2024-10-26 18:51 UTC, MikhayloBil commented
вже пофіксив

2024-10-26 22:33 UTC, AndriyITua approved these changes
Перевірено

2024-10-26 22:41 UTC, AndriyITua approved these changes
Перевірено

2024-10-26 23:25 UTC, AndriyITua approved these changes
Перевірено

2024-10-27 07:41 UTC, andrewwwmatsko requested changes
fetchUserByid і getUser роблять те ж сами, ми ж говорили
лиши якусь одну функцію з них і її юзай


Ти фетичиш юзера і з свого компонента і з хоум пейж, так не треба - вибери одне місце - наприклад homePage і все

якщо будеш лишати функцію getUser, тоді в слайді треба обробити і pending i rejected, а не тільки fulfilled

також в нас прописані всі селектори, користуйся ними

2024-10-27 09:28 UTC, andrewwwmatsko commented on src/redux/auth/operationUserId.js
> +      setAuthHeader(token);
забрати

2024-10-27 09:38 UTC, andrewwwmatsko approved these changes

2024-10-27 09:40 UTC, merged